export enum ComponentType {
  SLIDER_POSTS = "SLIDER_POSTS",
  WEEKEND_TOP = "WEEKEND_TOP",
  NEW_CONTENT_POSTS = "NEW_CONTENT_POSTS",
  CATEGORY_POSTS_1 = "CATEGORY_POSTS_1",
  CATEGORY_POSTS_2 = "CATEGORY_POSTS_2",
  RATING_POSTS = "RATING_POSTS",
  RANDOM_POSTS = "RANDOM_POSTS",
  DON_T_MISS_POSTS = "DON_T_MISS_POSTS",
  RECENT_POSTS = "RECENT_POSTS",
  READ_NEXT_POSTS = "READ_NEXT_POSTS",
  RECENT_COMMENTS = "RECENT_COMMENTS",
  POPULAR_POSTS = "POPULAR_POSTS",
  RELATED_POSTS = "RELATED_POSTS",
  CATEGORY_DETAIL = "CATEGORY_DETAIL",
  MANAGEMENT_POSTS = "POST MANAGEMENT"
}
