export enum ComponentType {
    SLIDER_POSTS = "SLIDER_POSTS",
    NEW_CONTENT_POSTS = "NEW_CONTENT_POSTS",
    CATEGORY_POSTS_1 = "CATEGORY_POSTS_1",
    CATEGORY_POSTS_2 = "CATEGORY_POSTS_2",
    RATING_POSTS = "RATING_POSTS",
    DON_T_MISS_POSTS = "DON_T_MISS_POSTS",
    RECENT_POSTS = "RECENT_POSTS",
    READ_NEXT_POSTS = "READ_NEXT_POSTS",
    RECENT_COMMENTS = "RECENT_COMMENTS",
    POPULAR_POSTS = "POPULAR_POSTS"
}
